### ISSUE TITLE
[Activity] Remove duplicate bought/sold to transactions from feed

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/bezos-frontend#219]
## Description
In the Activities feed on a project, when a tonne is sold, it looks like we are putting both transactions in the feed, i.e. we report "...bought from You" and "You sold to..." but these are essentially the same transaction.
![Image](https://user-images.githubusercontent.com/103535195/219761461-8d7b8ac6-9709-4067-a3ed-4f874f4716d4.png)

## Requirements
- [x] This is the same transaction. We should only show the "bought from" transaction. "Sold to" should not be shown.

![Image](https://user-images.githubusercontent.com/103535195/219762539-37fb5b1c-65d9-4051-a62e-296c37714f72.png)

**Comment by Najada** [comment]
@jabby09 https://www.carbonmark.com/projects/VCS-1764-2020 updated this - now Activity type Sold doesn't appear anymore on the feed.

**Comment by jabby09** [comment]
this is now resolved
