### ISSUE TITLE
[listings] Amounts less than 1 tonne are shown

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/bezos-frontend#397]
[This project ](https://www.carbonmark.com/projects/VCS-191-2008) has a listing by Jabby with only 0.03 tonnes available, which is impossible to purchase due to the minimum 1 tonne restriction. It results in an incorrect "lowest price" shown in the Projects tab.

![image](https://user-images.githubusercontent.com/99001851/227103918-272aaa8c-e5e6-4ba4-9104-9e67de7b7316.png)

**Comment by Atmosfearful** [comment]
closing in favor of KlimaDAO/klimadao#1035 

We can't easily hide <1 tonne listings right now because id have to add some logic to detect if the user is logged in and viewing their own profile (otherwise they wont be able to get their remaining kilograms back). We need a more robust solution
