### ISSUE TITLE
[projects] Projects need to support listings from multiple pools

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/bezos-frontend#435]
[Related discord thread](https://discord.com/channels/841390338324824096/1089902694329749606)

This was my starting point using VCS-981 "Pacajai" as a test case.
![image](https://user-images.githubusercontent.com/103535195/228350226-33f942dc-da09-4464-808b-abf534e6c436.png)

According to the carbon dashboard, there should be six projects, 4 in the NCT pool (2012, 2013, 2014, 2017) and 2 in the NBO pool (2014, 2017)
![image](https://user-images.githubusercontent.com/103535195/228350285-4b110c57-2bbb-4f5c-a4c3-90289542c714.png)
![image](https://user-images.githubusercontent.com/103535195/228350324-0e91e277-4449-4abd-8d0b-52403499b31d.png)

Here is a summary table of what I found when I click through each of these 6 projects in the marketplace.
![image](https://user-images.githubusercontent.com/103535195/228350382-ed615387-a727-4845-bf60-7307f8035297.png)

The issue I think is that we have projects detail pages with the same URL, i.e. they are not unique. 

What should be happening (I think) is there is ONE project card on the Marketplace for VCS-981-2014 (as an example) but it should have TWO listings on the details page, one for NCT and one for NBO. Since NCT pool is the best price, it should be shown as the top best price listing and that is also the price that should be reflected on the project card in the marketplace.

When I hit https://api.carbonmark.com/api/projects/VCS-981-2014 I only get the NCT pool result back.
When I hit https://api.carbonmark.com/api/projects/VCS-981-2017 I only get the NBO pool result back.

This is why we have this weirdness between the project cards and the project details pages/prices.

**Comment by Najada** [comment]
@jabby09 https://www.carbonmark.com/projects/VCS-981-2017 updated :)
now all the pool prices will appear there

**Comment by jabby09** [comment]
@Najada thanks, this is fixed for that specific project but still seeing weird things with these projects, see my comment in [discord thread](https://discord.com/channels/841390338324824096/1089902694329749606/1095786714695483422)

**Comment by jabby09** [comment]
this is now resolved
