### ISSUE TITLE
[data] Add sanity project data to the api endpoint

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/bezos-frontend#440]
There is data in our sanity instance that I'm not seeing on the API endpoint.

Two examples we need to make front end changes.
![image](https://user-images.githubusercontent.com/103535195/228654309-a328560f-e792-4b62-865d-93209a1e35d6.png)
![image](https://user-images.githubusercontent.com/103535195/228654345-978ba74b-d7e7-46f2-8bd6-d60cee38c4c5.png)

For reference, this is the sanity database https://carbon-projects.sanity.studio/desk/project
If i do an api call like this: https://api.carbonmark.com/api/projects/VCS-836-2018
I am not seeing Registry or URL in the returned data.

**Comment by Najada** [comment]
@jabby09 URL added from sanity cms. Registry is already coming from the chain

**Comment by jabby09** [comment]
thanks and closed
