### ISSUE TITLE
[connect] Inform user if on wrong network

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/bezos-frontend#46]
## Description

Right now, it is possible to use the Wallet on any network.

**CURRENT STATE**
If the net is not Mumbai => all transaction fail without telling the user that this is due to the wrong network.

## TODO
- [ ] extend the Connectmodal (or find a better place?) to inform the user if the network is not correct
- [ ] before launch => net is "mumbai", after launch => net is "polygon"

**Comment by Atmosfearful** [comment]
yeah let's copy it over from `site` everything should work the same. And then we migrate to `lib` in KlimaDAO/klimadao#1011
