### ISSUE TITLE
[frontend qa] First Pass Issues

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/bezos-frontend#67]
## Connecting and setting up

1. I was not prompted to switch networks after connecting my wallet.

2. I selected Metamask on Brave, and it automatically prompted the Brave wallet. I believe displaying both should only be an option when the MM extension is installed on Brave. Otherwise - just Brave wallet.

3. I was able to edit my profile without being on Mumbai (since I have the same signature across networks).

4. Changing the user manually in the URL to a different KNS (in [users](https://carbonmark.vercel.app/users/shimond.klima)) gives 404 error. I think it should display a page that says user does not exist.

5. "New lines" in 'About' are not showing under 'Display Name'.
![image](https://user-images.githubusercontent.com/99001851/213963783-2fbab3e3-4117-43f6-864b-eae1e713420f.png)
![image](https://user-images.githubusercontent.com/99001851/213963824-23c84d4e-bfc0-4086-be69-7bbde76073e8.png)

## Listing a project
6. I was able to submit an approval with a price of 0 USDC. This resulted in an error with an incorrect error message. Should add price trap of usdc>0.
![image](https://user-images.githubusercontent.com/99001851/213964071-366a7d35-93eb-4ef4-90c5-5609314a00e9.png)
![image](https://user-images.githubusercontent.com/99001851/213964092-1a2981db-1179-48d2-93a1-18fdb7bde101.png)

7. After attempting to change the price to $20, I'm still unable to approve. This is likely a backend issue, and approval shouldn't have anything to do with price - just the quantity and the token.
![image](https://user-images.githubusercontent.com/99001851/213964285-b997ca30-eedc-4f2f-bd45-58510c01dfdf.png)

**I'm stuck here in my QA of this category**

## Portfolio

8. My portfolio is empty, although I have both C3 tokens.
![image](https://user-images.githubusercontent.com/99001851/213964409-576b3e5b-c0be-4187-aa4d-b7ebce00b712.png)

**I'm stuck here in my QA of this category**

## Buy

9. I should not be able to type more than the amount available without a red warning/ gray out.
![image](https://user-images.githubusercontent.com/99001851/213964723-2a21f0b5-90e0-4eeb-924a-de1a9e970fd6.png)

10. I should not be able to type less than or equal to 0:
![image](https://user-images.githubusercontent.com/99001851/213964792-3dd8de62-f2bf-49c6-9df3-9036f0ee9a82.png)

11. Both buttons in the [receipt](https://carbonmark.vercel.app/purchases/0xfb8e756fe8048aa0861e98a97fb030e016020fc31341b15c4d07323038226219) aren't redirecting anywhere.
![image](https://user-images.githubusercontent.com/99001851/213965279-3f30eeda-95f8-42c6-aa9a-bf0cc812add0.png)

12. After buying 1 tonne out of 2 tonnes available, the inventory from the seller did not decrement.
![image](https://user-images.githubusercontent.com/99001851/213965450-9ef35163-6ab8-414c-bf11-7efc8e00e737.png)

**Comment by ShimonD-KlimaDAO** [comment]
> 4. KNS in URL
I meant that switching to a **different** KNS which doesn't have a profile does not gracefully display a "user does not exist" page. [Here](https://carbonmark.vercel.app/users/blankslate.klima) is an example - however, this may have been fixed since I no longer get 404 error, so we can mark it as complete.

> 9. I should not be able to type more than the amount available without a red warning/ gray out.
This doesn't seem to be resolved in PR KlimaDAO/bezos-frontend#54 . I tried both [this](https://carbonmark.vercel.app/) link, and [this](https://carbonmark-git-ladytrekker-purchase-with-balance-klimadao.vercel.app/projects/VCS-487-2013/purchase/0x19) link.
![image](https://user-images.githubusercontent.com/99001851/215620728-bb0eedf3-1eed-489c-b1c2-6c0c5b277cb6.png)

> 12. After buying 1 tonne out of 2 tonnes available, the inventory from the seller did not decrement.

[Here](https://mumbai.polygonscan.com/tx/0xfb8e756fe8048aa0861e98a97fb030e016020fc31341b15c4d07323038226219) is the original transaction. The listing had 2 tonnes before and after the transaction.
I was not able to replicate this, because I now encounter a new potential bug. I have close to `10,000` fake USDC, but I am unable to buy tonnage. My address is `0x6F9F81eb4f54512Be8c91833783ee0074328E062`
![image](https://user-images.githubusercontent.com/99001851/215621543-cd5483b6-6592-417e-9762-dca6cc276818.png)

**Comment by ladytrekker** [comment]
## **9. Exceed Available Amount**

> I should not be able to type more than the amount available without a red warning/ gray out.

As soon as try to submit => an error message appears.
If you change the value again, the validation happens on the fly.
This behaviour is due to the lib we are using (react-hook-forms).
Still, it is not possible to submit a purchase when you exceeded your amount.
I therefore do not consider this as a bug.

<img width="503" alt="Bildschirm­foto 2023-01-31 um 11 16 56" src="https://user-images.githubusercontent.com/95881624/215733262-3bc87d45-4de6-413c-9dc1-ed2ebde2f354.png">

**Comment by ShimonD-KlimaDAO** [comment]
> ## Exceed Available Balance (a new potential bug)
> I can not confirm this issue. To be super sure that the client reads the correct balance => I opened a PR which shows now the current USDC balance of the user's wallet => see screenshots and testing link in the PR KlimaDAO/bezos-frontend#81

I confirmed that this is fixed. I tried reproducing issue (12).

Before, we have 14 tonnes available:
![image](https://user-images.githubusercontent.com/99001851/216243130-7e5e947f-242f-4eb8-adfd-d7b589a815e6.png)

I [purchased](https://mumbai.polygonscan.com/tx/0xcd4c1de0db0b84cc43a1f0f673cda6217abbc6cda1a4ff9058cc96f475ad5158) 1 tonne.

I did not see the amount update for over a minute. Then it finally updated - **is the lag a concern?** 
In the meantime, I [purchased](https://mumbai.polygonscan.com/tx/0x944712adad2329e4996222dc8a306545726ae66aff701bd1c467736227b6ae27) another 5 tonnes, and got [this](https://carbonmark-git-ladytrekker-show-available-balance-klimadao.vercel.app/purchases/0x944712adad2329e4996222dc8a306545726ae66aff701bd1c467736227b6ae27):
![image](https://user-images.githubusercontent.com/99001851/216244245-b0bbe7fb-45d7-4ee2-be22-f918ed95c2f3.png)

I tried opening the lonk above in multiple browsers, and I see the same.

**Comment by ladytrekker** [comment]
## 500 on Purchase Link

Thanks, this was a bug from the API and is fixed now. ⭐ 
=> [LINK](https://carbonmark.vercel.app/purchases/0x944712adad2329e4996222dc8a306545726ae66aff701bd1c467736227b6ae27)
